- .github/workflows/add_issue_to_project.yml
Added to ensure that all issues opened against this repo land on the project board
> feat: add repo issues to project board

- libs/wallet-ui/src/components/header/header.tsx
- libs/wallet-ui/src/components/icons/edit.tsx
- libs/wallet-ui/src/components/icons/trash.tsx
- libs/wallet-ui/src/components/remove-wallet-dialog/index.tsx
- libs/wallet-ui/src/components/remove-wallet/index.tsx
- libs/wallet-ui/src/components/remove-wallet/remove-wallet.tsx
- libs/wallet-ui/src/components/wallet-edit/index.ts
- libs/wallet-ui/src/components/wallet-edit/wallet-edit.tsx
- libs/wallet-ui/src/contexts/global/global-actions.ts
- libs/wallet-ui/src/contexts/global/global-context.ts
- libs/wallet-ui/src/contexts/global/global-reducer.ts
- libs/wallet-ui/src/hooks/use-rename-wallet.tsx
- libs/wallet-ui/src/hooks/use-vega-home.tsx
- libs/wallet-ui/src/routes/wallet/home.tsx
- libs/wallet-ui/src/routes/wallet/index.tsx
Closes #21 
Copy the functionality from the desktop wallet, since it has been merged only there.
> feat: migrate wallet rename

- libs/wallet-ui/src/components/icons/edit.tsx
- libs/wallet-ui/src/components/icons/trash.tsx
- libs/wallet-ui/src/contexts/global/global-context.ts
- libs/wallet-ui/src/contexts/global/global-provider.tsx
- libs/wallet-ui/src/hooks/use-import-network.tsx
- libs/wallet-ui/src/hooks/use-window-size.ts
- libs/wallet-ui/src/routes/wallet-import/wallet-import.tsx
Closes #34 
Fixes the displaying the data on error messages.
> fix: error messages

- libs/wallet-ui/index.ts
- libs/wallet-ui/package.json
- libs/wallet-ui/project.json
- libs/wallet-ui/src/components/telemetry-dialog/telemetry-dialog.tsx
- libs/wallet-ui/src/contexts/global/global-provider.tsx
- libs/wallet-ui/src/types/features.ts
Need this in order to be able to resolve the broken pipeline in https://github.com/vegaprotocol/vegawallet-desktop/pull/435
> chore: telemetry feature flag

- libs/wallet-ui/package.json
- libs/wallet-ui/src/__mocks__/service.ts
- libs/wallet-ui/src/components/network-compatibility-dialog/network-compatibility-dialog.tsx
- libs/wallet-ui/src/types/service.ts
> fix: wails version type

- libs/wallet-client/package.json
- libs/wallet-client/src/__generated__/index.ts
- libs/wallet-client/src/__generated__/mock.ts
- libs/wallet-client/template/index.ts
Closes #54 
Fix empty params issue based on https://github.com/vegaprotocol/frontend-monorepo/pull/2462#discussion_r1056544802
> fix: wallet client empty params

- libs/wallet-ui/package.json
- libs/wallet-ui/src/components/chrome/chrome-drawer.tsx
- libs/wallet-ui/src/components/chrome/chrome.tsx
- libs/wallet-ui/src/components/chrome/drawer-head.tsx
- libs/wallet-ui/src/components/forms/select.tsx
- libs/wallet-ui/src/components/radio-group/radio-group.tsx
- libs/wallet-ui/src/components/splash-loader/splash-loader.tsx
- libs/wallet-ui/src/components/toaster/toaster.tsx
- libs/wallet-ui/src/routes/home/home.tsx
Related to #53 
Added some post-merge fixes to patch up some styles which i realised were broken when importing the new ui release into the desktop wallet.
> fix: some broken styles

- libs/wallet-client/README.md
- libs/wallet-client/package.json
- libs/wallet-client/src/__generated__/index.ts
- libs/wallet-client/src/__generated__/mock.ts
- libs/wallet-client/template/index.ts
Closes #56 
Improves the error handling for the wallet client by adding `WalletClientError` and `WalletHttpError` wrappers.
> chore: client errors

- libs/wallet-client/package.json
- libs/wallet-client/src/__generated__/index.ts
- libs/wallet-client/src/__generated__/mock.ts
- libs/wallet-client/src/index.spec.ts
- libs/wallet-client/template/index.ts
Add callback for token change so consumers can easily update their saved tokens when necessary.
> chore: bump client

- libs/wallet-ui/package.json
- libs/wallet-ui/src/__mocks__/service.ts
- libs/wallet-ui/src/app-loader.tsx
- libs/wallet-ui/src/contexts/global/global-actions.ts
- libs/wallet-ui/src/contexts/global/global-context.ts
- libs/wallet-ui/src/contexts/global/global-reducer.ts
- libs/wallet-ui/src/types/service.ts
Solves https://github.com/vegaprotocol/vegawallet-desktop/issues/422
Add new handler to call as a result of the updated desktop wallet backend interface change
> fix: add handler for backend startup

- libs/wallet-ui/src/components/wallet-edit/wallet-edit.tsx
- libs/wallet-ui/src/routes/wallet/home.tsx
Adding testids to ease testing.
> chore: add testid for edit wallet button and form

- libs/wallet-ui/package.json
> chore: bump wallet-ui version

- libs/wallet-ui/package.json
- libs/wallet-ui/src/components/chrome/service-status.tsx
Closes n/a
Fix duplicated service url
> fix: service url

- libs/wallet-ui/package.json
- libs/wallet-ui/src/components/chrome/service-status.tsx
- libs/wallet-ui/src/components/network-compatibility-dialog/network-compatibility-dialog.tsx
- libs/wallet-ui/src/contexts/global/global-context.ts
- libs/wallet-ui/src/contexts/global/global-reducer.ts
Closes https://github.com/vegaprotocol/vegawallet-desktop/issues/507
Adjust the network compatibility dialog so it doesn't pop up every time it detects the network is not compatible, but displays a clickable warning icon in the service status bar instead
> feat: rework network warning

- .github/workflows/cypress-test.yml
- apps/wallet-mock/cypress.config.ts
- apps/wallet-mock/project.json
- package.json
Add cypress run to github workflows.
> chore: create cypress workflow

- .github/workflows/cypress-test.yml
It won't work with current structure.
> chore: remove nx affected from cypress workflow

- apps/wallet-mock/index.d.ts
- apps/wallet-mock/src/support/index.ts
- apps/wallet-mock/src/test/network-compatibility.cy.ts
- apps/wallet-mock/src/test/telemetry.cy.ts
- apps/wallet-mock/src/types/admin-mock.ts
- apps/wallet-mock/src/types/service-mock.ts
- libs/wallet-ui/src/__mocks__/service.ts
- libs/wallet-ui/src/components/chrome/service-status.tsx
- libs/wallet-ui/src/components/dialog/dialog.tsx
- libs/wallet-ui/src/components/network-compatibility-dialog/network-compatibility-dialog.tsx
- libs/wallet-ui/src/components/telemetry-dialog/telemetry-dialog.tsx
Relates to https://github.com/vegaprotocol/vegawallet-desktop/issues/478
This PR is mainly about covering https://github.com/vegaprotocol/specs/blob/master/user-interface/0001-WALL-wallet.md#0001-WALL-015 and all details of network incompatibility dialog.
Also fixed one minor bug related to displaying compatible networks.
> test: add network compatibility check tests

- libs/wallet-ui/src/index.tsx
- libs/wallet-ui/src/routes/home/home.tsx
- libs/wallet-ui/tailwind.config.js
- package.json
- yarn.lock
Related to https://github.com/vegaprotocol/vegawallet-desktop/issues/542
Integrate UI toolkit with the existing wallet app for consistent design experience
N/A
- Priority is given to the existing configuration at the moment
- We can pare this down as time goes on
- Uses the published packages from the frontend monorepo
> feat: ui toolkit integration

- apps/wallet-mock/index.d.ts
- apps/wallet-mock/src/support/event-trigger.ts
- apps/wallet-mock/src/support/mock.ts
- apps/wallet-mock/src/test/service.cy.ts
- apps/wallet-mock/src/test/transaction.cy.ts
- libs/wallet-ui/src/components/interactions/flows/transaction-review/transaction-review.tsx
- libs/wallet-ui/src/components/spinner/spinner.tsx
- libs/wallet-ui/src/components/transaction-details/transaction-details.tsx
- libs/wallet-ui/src/components/transaction-status/transaction-status.tsx
- libs/wallet-ui/test/index.tsx
Closes #104 
Added Cypress function that trigger Transaction Review event.
Covered [0001-WALL-024](https://github.com/vegaprotocol/specs/blob/master/user-interface/0001-WALL-wallet.md#0001-WALL-024) and [0001-WALL-025](https://github.com/vegaprotocol/specs/blob/master/user-interface/0001-WALL-wallet.md#0001-WALL-025).
> test: added interaction mock with review transaction tests

- apps/wallet-mock/src/test/dapp-connect.test.ts
- apps/wallet-mock/src/test/dapp-remove-connection.test.ts
- apps/wallet-mock/src/test/network-compatibility.test.ts
- apps/wallet-mock/src/test/telemetry.test.ts
- libs/wallet-ui/src/components/connection-list/connection-item.tsx
- libs/wallet-ui/src/components/connection-list/connection-list.tsx
- libs/wallet-ui/src/components/connection-list/connection-remove.tsx
- libs/wallet-ui/src/components/interactions/flows/wallet-connection/views/connection.tsx
- libs/wallet-ui/src/components/interactions/flows/wallet-connection/views/passphrase.tsx
- libs/wallet-ui/src/components/interactions/flows/wallet-connection/views/selection.tsx
- libs/wallet-ui/src/components/interactions/views/success.tsx
- libs/wallet-ui/src/routes/wallet/home.tsx
Closes #124 
Wallet connection flow modals are covered now with UI tests.
> test: cover acs related to wallet connect modal

- libs/wallet-ui/jest.config.ts
- libs/wallet-ui/src/components/button-group/button-group.test.tsx
- libs/wallet-ui/src/components/button-group/button-group.tsx
N/A
Get an insight in the amount of code coverage we are getting currently
> chore: coverage collection, fix missed coverage paths

- libs/wallet-ui/src/__stories__/app.stories.tsx
- libs/wallet-ui/src/components/chrome/chrome-drawer.tsx
- libs/wallet-ui/src/components/chrome/chrome.tsx
- libs/wallet-ui/src/contexts/global/global-provider.tsx
- libs/wallet-ui/src/hooks/use-is-fairground.tsx
- libs/wallet-ui/src/routes/onboard/onboard.stories.tsx
- libs/wallet-ui/src/routes/onboard/onboard.tsx
- libs/wallet-ui/src/types/features.ts
N/A
Adds fairground feature flag to allow for rendering of custom testnet specific UI
> feat: add fairground feature flag

- libs/wallet-ui/package.json
- libs/wallet-ui/src/hooks/use-create-wallet.tsx
- libs/wallet-ui/src/hooks/use-import-wallet.tsx
- libs/wallet-ui/src/routes/onboard/start.tsx
> chore: only call initialise app if not initialised

- libs/wallet-ui/package.json
- libs/wallet-ui/src/routes/onboard/home.tsx
N/A
Pre-populate field with suggested vega home
> feat: prepopulate vegahome field

- libs/wallet-ui/package.json
- libs/wallet-ui/src/app-loader.tsx
- libs/wallet-ui/src/contexts/global/global-actions.ts
- libs/wallet-ui/src/hooks/use-create-wallet.tsx
- libs/wallet-ui/src/hooks/use-import-wallet.tsx
- libs/wallet-ui/src/routes/onboard/home.tsx
- libs/wallet-ui/src/routes/onboard/start.tsx
Closes #[Issue number here]
A description of what this PR does. This should be non-dev readable. Technical stuff should go in the technical section below.
Gif/video/images of new/corrected functionality if applicable
Details of technical implementation that reviewers may need to be aware of, if applicable.
> chore: do not render use exisitng method if fairground
